# Always run on tmux
if [ -z "$TMUX" ]
then
  tmux
else

  stty -ixon

  ### PROMPT ###

  # If not running interactively, don't do anything
  [ -z "$PS1" ] && return

  # Custom prompt
  PS1="🍪 :\W "

  # Space expands commands before executing them
  bind Space:magic-space
  # Set terminal colors
  export TERM=screen-256color

  ## PATHS ###

  # Homebrew?
  export PATH=~/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/X11/bin

  # Texlive
  export PATH="/usr/local/texlive/2015basic/bin/universal-darwin:$PATH"

  # Rust
  export PATH="/Users/Kevin/.cargo/bin:$PATH"
  ### LOADERS

  # OPAM configuration
  . /Users/Kevin/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  # NVM
  export NVM_DIR="/Users/Kevin/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

  # mysql vanilla
  PATH=${PATH}:/usr/local/mysql/bin

  # Go
  # export GOROOT=/usr/lcoal/opt/go/libexec
  export GOPATH="$HOME/Sites/go"
  export PATH="$PATH:$GOPATH/bin"

  # RVM things
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
  export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

  ### History ###

  HISTCONTROL=ignoreboth:erasedups # dont include duplicate lines + lines starting with space
  shopt -s histappend # append to the history file, don't overwrite it
  HISTSIZE=1000
  HISTFILESIZE=2000

  # If set, the pattern "**" used in a pathname expansion context will
  # match all files and zero or more directories and subdirectories.
  #shopt -s globstar

  ### Other Sources ###

  # Alias definitions.
  [ -f "$HOME/.bash_aliases" ] && . "$HOME/.bash_aliases"

  # Source .bashrc
  [ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"

  ### Misc ###

  # For more github searches on Homebrew
  export HOMEBREW_GITHUB_API_TOKEN=edc857c1e994cabab884168ed8983da5e781cbe5

  # Git autocomplete branch names
  [ -f "$HOME/.git-completion.bash" ] && . "$HOME/.git-completion.bash"

  # For playing video on terminal using libcaca
  CACA_DRIVER=ncurses

  # OPAM configuration
  . /Users/Kevin/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

  # iTerm2 shell integration
  test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

  ### for the lolz ###
  date | figlet | lolcat

fi
