case "$OSTYPE" in
  darwin*)
    ;; 
  linux*)
    echo "LINUX"
    ;;
  bsd*)
    echo "BSD"
    ;;
  *)   
    echo "unknown: $OSTYPE"
    ;;
esac

# PATH (Homebrew, I think)
export PATH=~/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/usr/X11/bin
export PATH="$HOME/Library/Haskell/bin:$PATH"
export PATH="usr/local/texlive/2014/bin/x86_64-darwin:$PATH"
export PATH="$PATH:/usr/local/texlive/2014/bin/x86_64-darwin"

# Custom prompt: http://osxdaily.com/2013/04/08/add-emoji-command-line-bash-prompt/
# 		 http://osxdaily.com/2006/12/11/how-to-customize-your-terminal-prompt/

PS1="🍪 :\W "

###
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls -G'
  #alias dir='dir --color=auto'
  #alias vdir='vdir --color=auto'
  #alias grep='grep --color=auto'
  #alias fgrep='fgrep --color=auto'
  #alias egrep='egrep --color=auto'
fi

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

###


# Color: http://stackoverflow.com/questions/1550288/mac-os-x-terminal-colors
export CLICOLOR=1
# export LSCOLORS=GxFxCxDxBxegedabagaced
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# For more github searches on Homebrew
export HOMEBREW_GITHUB_API_TOKEN=edc857c1e994cabab884168ed8983da5e781cbe5

# Ruby env?
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# OPAM configuration
. /Users/Kevin/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

export NVM_DIR="/Users/Kevin/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
